-- 홈 배너 인사이트 문구(힐링/명언/기능가이드/통계템플릿) -- 2026-08-01 사용자 지시("출시전에", 백엔드로 이전).
-- 예전엔 src/services/insightContent.ts에 하드코딩돼 있어서 문구 하나 고치려면 앱스토어 재배포가
-- 필요했다. 이 테이블로 옮겨서 SQL만 바꾸면 앱 업데이트 없이 문구를 추가/수정/비활성화할 수 있다.
-- category: healing | quote | tip | stat_yesterdayLastWatched | stat_todayMoreThanAvg | stat_todayLessThanAvg
-- stat_* 세 카테고리는 {{time}}/{{diff}} 플레이스홀더를 포함하며 클라이언트가 실제 값으로 치환한다.
CREATE TABLE insight_item (
    id         BIGINT AUTO_INCREMENT PRIMARY KEY,
    category   VARCHAR(32)  NOT NULL,
    text_en    VARCHAR(500) NOT NULL,
    text_ko    VARCHAR(500) NOT NULL,
    active     BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_insight_item_category ON insight_item (category, active);

INSERT INTO insight_item (category, text_en, text_ko, active) VALUES ('healing', 'You don''t have to finish everything today. Tomorrow will still be there', '오늘 다 끝내지 않아도 괜찮아요. 내일도 여전히 있어요', TRUE);
INSERT INTO insight_item (category, text_en, text_ko, active) VALUES ('healing', 'Resting is not falling behind. It''s part of the pace', '쉬는 건 뒤처지는 게 아니에요. 그것도 페이스의 일부예요', TRUE);
INSERT INTO insight_item (category, text_en, text_ko, active) VALUES ('healing', 'A quiet five minutes can reset more than you think', '조용한 5분이 생각보다 많은 걸 다시 채워줘요', TRUE);
INSERT INTO insight_item (category, text_en, text_ko, active) VALUES ('healing', 'You''re doing better than the version of you from last week', '지금의 나는 지난주의 나보다 조금 더 나아졌어요', TRUE);
INSERT INTO insight_item (category, text_en, text_ko, active) VALUES ('healing', 'Not every scroll needs a reason. But rest does deserve one too', '모든 스크롤에 이유가 필요한 건 아니지만, 쉬는 것도 이유가 될 자격이 있어요', TRUE);
INSERT INTO insight_item (category, text_en, text_ko, active) VALUES ('healing', 'It''s okay to put the phone down mid-video. It''ll still be there', '영상 보다가 그냥 꺼도 괜찮아요. 나중에 또 있어요', TRUE);
INSERT INTO insight_item (category, text_en, text_ko, active) VALUES ('healing', 'Small pace, steady pace. That''s still progress', '느린 걸음도 꾸준하면 그게 나아가는 거예요', TRUE);
INSERT INTO insight_item (category, text_en, text_ko, active) VALUES ('healing', 'Nobody''s keeping score except the algorithm. You can log off', '점수 매기는 건 알고리즘뿐이에요. 언제든 로그아웃해도 돼요', TRUE);
INSERT INTO insight_item (category, text_en, text_ko, active) VALUES ('healing', 'Your evening doesn''t owe anyone a highlight reel', '오늘 저녁이 꼭 하이라이트일 필요는 없어요', TRUE);
INSERT INTO insight_item (category, text_en, text_ko, active) VALUES ('healing', 'Breathe. You''re allowed to just exist without producing anything right now', '숨 한번 쉬어요. 지금 당장 뭔가 만들어내지 않아도 괜찮아요', TRUE);
INSERT INTO insight_item (category, text_en, text_ko, active) VALUES ('healing', '"Just one more video" has never once meant one more video', '"딱 하나만 더 볼게"는 한 번도 하나만 본 적이 없죠', TRUE);
INSERT INTO insight_item (category, text_en, text_ko, active) VALUES ('healing', 'The algorithm has known you for years. It still can''t guess when to stop', '알고리즘은 나를 몇 년째 지켜봤으면서, 언제 멈춰야 하는지는 끝까지 몰라요', TRUE);
INSERT INTO insight_item (category, text_en, text_ko, active) VALUES ('healing', 'You checked the time and it lied to you. That''s just how Shorts work', '시계를 봤는데 거짓말인 줄 알았죠. 원래 쇼츠는 그런 거예요', TRUE);
INSERT INTO insight_item (category, text_en, text_ko, active) VALUES ('healing', 'Autoplay is not a personal invitation. You can decline', '자동재생은 초대장이 아니에요. 거절해도 됩니다', TRUE);
INSERT INTO insight_item (category, text_en, text_ko, active) VALUES ('healing', 'Your phone battery hit 20% before you did. Follow its lead — go charge', '폰 배터리가 나보다 먼저 20%가 됐어요. 그 신호 따라서 나도 좀 충전하죠', TRUE);
INSERT INTO insight_item (category, text_en, text_ko, active) VALUES ('healing', 'Somewhere out there, someone is watching the exact same 9-second clip on a loop. You''re not alone', '지금 이 순간, 누군가도 똑같은 9초짜리 영상을 무한 반복으로 보고 있어요. 혼자가 아니에요', TRUE);
INSERT INTO insight_item (category, text_en, text_ko, active) VALUES ('healing', 'The video ended 40 minutes ago in spirit. Only the app disagrees', '마음속으로는 40분 전에 끝났어요. 앱만 아직 모르고 있을 뿐', TRUE);
INSERT INTO insight_item (category, text_en, text_ko, active) VALUES ('healing', 'Comparing your day to a highlight reel is like comparing a whole meal to a food photo', '내 하루를 남의 하이라이트 영상과 비교하는 건, 밥 한 끼를 음식 사진이랑 비교하는 거예요', TRUE);
INSERT INTO insight_item (category, text_en, text_ko, active) VALUES ('healing', 'FOMO is just your brain''s worst travel agent. It always overbooks', 'FOMO는 뇌가 고용한 최악의 여행사예요. 맨날 일정을 과하게 잡아요', TRUE);
INSERT INTO insight_item (category, text_en, text_ko, active) VALUES ('healing', 'Doing nothing for ten minutes has never once ruined anyone''s life. Try it', '10분 동안 아무것도 안 한다고 인생이 망한 사람은 없어요. 한번 해봐요', TRUE);
INSERT INTO insight_item (category, text_en, text_ko, active) VALUES ('healing', 'Your to-do list will forgive you for one slow afternoon. It always does', '할 일 목록은 나른한 오후 한 번쯤은 용서해줘요. 늘 그래왔듯이', TRUE);
INSERT INTO insight_item (category, text_en, text_ko, active) VALUES ('healing', 'The remote control has a pause button for a reason — mostly for snacks, but also for you', '리모컨에 일시정지 버튼이 있는 건 다 이유가 있어요 — 주로 간식용이지만 나를 위한 것이기도 해요', TRUE);
INSERT INTO insight_item (category, text_en, text_ko, active) VALUES ('healing', 'You are not "behind." There was never a race', '당신은 "뒤처진" 게 아니에요. 애초에 경주 같은 건 없었어요', TRUE);
INSERT INTO insight_item (category, text_en, text_ko, active) VALUES ('healing', 'Somewhere a notification just went off. It can wait. So can the next one', '어딘가에서 방금 알림이 울렸어요. 좀 기다려도 돼요. 다음 것도요', TRUE);
INSERT INTO insight_item (category, text_en, text_ko, active) VALUES ('healing', 'Boredom is not an emergency. You are allowed to sit in it', '지루함은 응급상황이 아니에요. 그냥 그 안에 앉아 있어도 괜찮아요', TRUE);
INSERT INTO insight_item (category, text_en, text_ko, active) VALUES ('healing', 'Your couch has seen you binge-watch and it has never once judged you. Give it credit', '소파는 내가 정주행하는 걸 다 봤으면서 한 번도 뭐라 한 적 없어요. 그 정도는 인정해줘야죠', TRUE);
INSERT INTO insight_item (category, text_en, text_ko, active) VALUES ('healing', 'Nobody remembers the 47th video in a row. Memory has standards', '연달아 본 47번째 영상은 아무도 기억 못 해요. 기억력도 나름의 기준이 있거든요', TRUE);
INSERT INTO insight_item (category, text_en, text_ko, active) VALUES ('healing', 'You survived every single "I''ll just check one thing" so far. Impressive track record', '"딱 하나만 확인할게"를 지금까지 다 살아남았어요. 꽤 대단한 기록이에요', TRUE);
INSERT INTO insight_item (category, text_en, text_ko, active) VALUES ('healing', 'A screen break is not a punishment. It''s just a screen break', '화면 쉬는 시간은 벌이 아니에요. 그냥 쉬는 시간일 뿐이에요', TRUE);
INSERT INTO insight_item (category, text_en, text_ko, active) VALUES ('healing', 'The next video will still be recommended to you tomorrow. It is extremely patient', '다음 영상은 내일도 추천될 거예요. 알고리즘은 놀라울 정도로 끈질기거든요', TRUE);
INSERT INTO insight_item (category, text_en, text_ko, active) VALUES ('healing', 'Silence is not a bug in your day. It''s a feature you forgot you had', '조용한 시간은 하루의 오류가 아니에요. 원래 있었는데 잊고 있던 기능이에요', TRUE);
INSERT INTO insight_item (category, text_en, text_ko, active) VALUES ('healing', 'You don''t need permission to close the app. Consider this it, if you were waiting', '앱을 끄는 데 허락은 필요 없어요. 혹시 기다리고 있었다면, 지금 이게 그 허락이에요', TRUE);
INSERT INTO insight_item (category, text_en, text_ko, active) VALUES ('healing', 'One unfinished video does not count against you anywhere. There''s no scoreboard', '끝까지 안 본 영상 하나, 어디에도 감점으로 안 남아요. 점수판 자체가 없거든요', TRUE);
INSERT INTO insight_item (category, text_en, text_ko, active) VALUES ('healing', 'Your eyes have been staring at a rectangle for a while. They''d probably vote for a window right now', '눈이 한참 동안 네모난 화면만 보고 있었어요. 지금 물어보면 창밖을 보고 싶다고 할걸요', TRUE);
INSERT INTO insight_item (category, text_en, text_ko, active) VALUES ('healing', 'Every "last one" is a promise. You''re allowed to actually keep it', '"마지막 하나"는 약속이에요. 그 약속, 진짜로 지켜도 괜찮아요', TRUE);
INSERT INTO insight_item (category, text_en, text_ko, active) VALUES ('healing', 'The internet will still be exactly this loud tomorrow. No need to catch up on all of it today', '인터넷은 내일도 딱 이만큼 시끄러울 거예요. 오늘 다 따라잡을 필요 없어요', TRUE);
INSERT INTO insight_item (category, text_en, text_ko, active) VALUES ('healing', 'You are allowed to be unproductive on purpose. That''s a real setting, not a failure', '일부러 아무것도 안 하는 것도 괜찮은 선택이에요. 실패가 아니라 하나의 설정값이에요', TRUE);
INSERT INTO insight_item (category, text_en, text_ko, active) VALUES ('healing', 'Somewhere, someone is jealous of the amount of rest you''re about to take. Take it anyway', '어딘가에는 지금 내가 취할 휴식을 부러워할 사람도 있어요. 그래도 그냥 쉬세요', TRUE);
INSERT INTO insight_item (category, text_en, text_ko, active) VALUES ('healing', 'A closed tab has never once haunted anyone. Close it', '닫힌 탭이 사람을 쫓아온 적은 없어요. 그냥 닫아도 돼요', TRUE);
INSERT INTO insight_item (category, text_en, text_ko, active) VALUES ('healing', 'Time you don''t remember spending is still time you spent. Worth checking in on', '기억도 안 나는 시간도 결국 쓴 시간이에요. 한 번쯤 점검해볼 만해요', TRUE);
INSERT INTO insight_item (category, text_en, text_ko, active) VALUES ('healing', 'Your future self already forgives you for tonight. Might as well wrap up a little early', '미래의 나는 오늘 밤의 나를 이미 용서했어요. 그럼 조금 일찍 마무리해도 괜찮겠네요', TRUE);
INSERT INTO insight_item (category, text_en, text_ko, active) VALUES ('healing', 'The video thumbnail lied about how short it would be. It always does', '썸네일은 늘 짧아 보이겠다고 속여요. 원래 그런 거예요', TRUE);
INSERT INTO insight_item (category, text_en, text_ko, active) VALUES ('healing', 'Real life doesn''t have a skip-ad button, but it does have a pause. Use it more often', '현실엔 광고 건너뛰기는 없지만 일시정지는 있어요. 좀 더 자주 써봐요', TRUE);
INSERT INTO insight_item (category, text_en, text_ko, active) VALUES ('healing', 'Not watching something is also a choice, and a perfectly good one', '안 보는 것도 하나의 선택이에요, 그것도 꽤 괜찮은 선택', TRUE);
INSERT INTO insight_item (category, text_en, text_ko, active) VALUES ('healing', 'You don''t need main-character energy today. Supporting-character rest is just as valid', '오늘은 꼭 주인공처럼 애쓰지 않아도 돼요. 조연처럼 쉬는 것도 똑같이 소중해요', TRUE);
INSERT INTO insight_item (category, text_en, text_ko, active) VALUES ('healing', 'The recommended-for-you list was never actually about you. It''s about your last 40 minutes', '추천 목록은 사실 "나"를 아는 게 아니에요. 최근 40분을 아는 거죠', TRUE);
INSERT INTO insight_item (category, text_en, text_ko, active) VALUES ('healing', 'A stretch break burns more regret than the video ever will burn calories', '스트레칭 한 번이 영상이 태우는 칼로리보다 후회를 더 많이 태워줘요', TRUE);
INSERT INTO insight_item (category, text_en, text_ko, active) VALUES ('healing', 'You clicked "not interested" and it recommended the same thing in a different color. You are stronger than that trick', '"관심 없음"을 눌렀는데 색깔만 바뀐 게 또 떴죠. 그 수법보다 내가 더 강해요', TRUE);
INSERT INTO insight_item (category, text_en, text_ko, active) VALUES ('healing', 'Somewhere between video 12 and video 13, you stopped choosing and started drifting. Choose again', '12번째와 13번째 영상 사이 어디쯤에서 선택은 멈추고 그냥 떠밀려 왔어요. 다시 선택해봐요', TRUE);
INSERT INTO insight_item (category, text_en, text_ko, active) VALUES ('healing', 'The couch is not going anywhere. Neither is the app. Only your evening is limited', '소파는 어디 안 가요. 앱도 마찬가지고요. 한정판인 건 오늘 저녁뿐이에요', TRUE);
INSERT INTO insight_item (category, text_en, text_ko, active) VALUES ('healing', 'You don''t owe the app a goodbye video. Just leave', '앱한테 작별 영상 하나 남길 필요 없어요. 그냥 나가면 돼요', TRUE);
INSERT INTO insight_item (category, text_en, text_ko, active) VALUES ('healing', 'Ten more seconds of a video rarely turns into ten more seconds', '"10초만 더"는 거의 언제나 10초로 안 끝나요', TRUE);
INSERT INTO insight_item (category, text_en, text_ko, active) VALUES ('healing', 'A short walk has a worse thumbnail than the next video, but a much better ending', '짧은 산책은 썸네일이 다음 영상보다 별로지만, 결말은 훨씬 나아요', TRUE);
INSERT INTO insight_item (category, text_en, text_ko, active) VALUES ('healing', 'You are not required to have an opinion on every video the internet made today', '오늘 인터넷이 만든 영상 전부에 의견을 낼 필요는 없어요', TRUE);
INSERT INTO insight_item (category, text_en, text_ko, active) VALUES ('healing', 'The play button will be exactly where you left it. It has nowhere else to be', '재생 버튼은 내가 떠난 자리에 그대로 있을 거예요. 어디 갈 데도 없거든요', TRUE);
INSERT INTO insight_item (category, text_en, text_ko, active) VALUES ('healing', 'One good stopping point beats ten "almost done" ones', '괜찮은 종료 지점 하나가 "거의 다 봄" 열 번보다 나아요', TRUE);
INSERT INTO insight_item (category, text_en, text_ko, active) VALUES ('healing', 'You can love something and still put it down. Those two things are not opposites', '좋아하면서도 내려놓을 수 있어요. 두 가지가 서로 반대되는 게 아니거든요', TRUE);
INSERT INTO insight_item (category, text_en, text_ko, active) VALUES ('healing', 'The next video always promises to be the best one. It has said that every single time', '다음 영상은 늘 최고일 거라고 약속해요. 그 말, 매번 했었죠', TRUE);
INSERT INTO insight_item (category, text_en, text_ko, active) VALUES ('healing', 'You don''t need a reason to log off. "I wanted to" already counts', '로그아웃하는 데 이유 같은 거 필요 없어요. "그냥 그러고 싶어서"면 충분해요', TRUE);
INSERT INTO insight_item (category, text_en, text_ko, active) VALUES ('healing', 'Whatever you were about to watch will survive being watched tomorrow instead', '보려던 그 영상, 내일 봐도 멀쩡할 거예요', TRUE);
INSERT INTO insight_item (category, text_en, text_ko, active) VALUES ('healing', 'Somewhere in the last hour, a stretch, a glass of water, or a nap was quietly postponed. It''s still available', '지난 한 시간 어딘가에서 스트레칭이나 물 한 잔, 낮잠 같은 게 조용히 미뤄졌어요. 아직 늦지 않았어요', TRUE);
INSERT INTO insight_item (category, text_en, text_ko, active) VALUES ('healing', 'A pause is not a failure state. It''s just the button next to play', '일시정지는 실패한 상태가 아니에요. 그냥 재생 버튼 옆에 있는 버튼일 뿐이에요', TRUE);
INSERT INTO insight_item (category, text_en, text_ko, active) VALUES ('healing', 'You can close this and open something slower. Slower still counts', '이걸 닫고 더 느린 걸 열어도 돼요. 느린 것도 여전히 유효해요', TRUE);
INSERT INTO insight_item (category, text_en, text_ko, active) VALUES ('healing', 'Today does not need a perfect ending. A closed app is a fine one', '오늘이 완벽하게 끝날 필요는 없어요. 앱 하나 끄는 것도 충분히 괜찮은 마무리예요', TRUE);
INSERT INTO insight_item (category, text_en, text_ko, active) VALUES ('healing', 'A five-second countdown before autoplay is basically the app asking permission. You''re allowed to say no', '자동재생 전 5초 카운트다운은 사실 앱이 허락을 구하는 거예요. "아니"라고 해도 돼요', TRUE);
INSERT INTO insight_item (category, text_en, text_ko, active) VALUES ('healing', 'Your attention is the one thing every app in your pocket is quietly competing for. You get to decide who wins today', '내 관심은 폰 속 모든 앱이 조용히 서로 가지려는 거예요. 오늘 누구한테 줄지는 내가 정해요', TRUE);
INSERT INTO insight_item (category, text_en, text_ko, active) VALUES ('healing', 'The version of you an hour from now is rooting for the version of you right now to stop a little early', '한 시간 뒤의 나는 지금의 내가 조금 일찍 멈추길 응원하고 있어요', TRUE);
INSERT INTO insight_item (category, text_en, text_ko, active) VALUES ('healing', 'Watching less is not the same as missing out. Most days, it''s the opposite', '덜 보는 게 놓치는 것과 같지 않아요. 오히려 대부분은 그 반대예요', TRUE);
INSERT INTO insight_item (category, text_en, text_ko, active) VALUES ('quote', '"The time you enjoy wasting is not wasted time." — Bertrand Russell', '"즐기면서 흘려보낸 시간은 낭비한 시간이 아니다." — 버트런드 러셀', TRUE);
INSERT INTO insight_item (category, text_en, text_ko, active) VALUES ('quote', '"Almost everything will work again if you unplug it for a few minutes, including you." — Anne Lamott', '"거의 모든 것은 잠깐 꺼두면 다시 잘 작동한다, 당신을 포함해서." — 앤 라모트', TRUE);
INSERT INTO insight_item (category, text_en, text_ko, active) VALUES ('quote', '"You don''t have to control your thoughts. You just have to stop letting them control you." — Dan Millman', '"생각을 통제할 필요는 없다. 그 생각이 나를 통제하지 못하게만 하면 된다." — 댄 밀먼', TRUE);
INSERT INTO insight_item (category, text_en, text_ko, active) VALUES ('quote', '"Slow down and everything you are chasing will come around and catch you." — John De Paola', '"천천히 가면, 쫓던 것들이 오히려 나를 따라온다." — 존 드 파올라', TRUE);
INSERT INTO insight_item (category, text_en, text_ko, active) VALUES ('quote', '"Rest is not idleness." — John Lubbock', '"쉼은 게으름이 아니다." — 존 러벅', TRUE);
INSERT INTO insight_item (category, text_en, text_ko, active) VALUES ('quote', '"You can''t pour from an empty cup." — unknown', '"빈 잔에서는 아무것도 따를 수 없다." — 작자 미상', TRUE);
INSERT INTO insight_item (category, text_en, text_ko, active) VALUES ('quote', '"Nothing is more expensive than a missed opportunity to rest." — H. Jackson Brown Jr.', '"쉴 기회를 놓치는 것보다 비싼 건 없다." — H. 잭슨 브라운 주니어', TRUE);
INSERT INTO insight_item (category, text_en, text_ko, active) VALUES ('quote', '"It is not the daily increase but daily decrease. Hack away at the unessential." — Bruce Lee', '"매일 더하는 게 아니라 매일 덜어내는 것이다. 불필요한 것을 쳐내라." — 브루스 리', TRUE);
INSERT INTO insight_item (category, text_en, text_ko, active) VALUES ('quote', '"The present moment is the only time over which we have dominion." — Thích Nhất Hạnh', '"현재 순간이야말로 우리가 다스릴 수 있는 유일한 시간이다." — 틱낫한', TRUE);
INSERT INTO insight_item (category, text_en, text_ko, active) VALUES ('quote', '"Half of the harm that is done in this world is due to people who want to feel important." — T. S. Eliot', '"세상에서 벌어지는 해악의 절반은 중요한 사람이 되고 싶어 하는 이들 때문이다." — T. S. 엘리엇', TRUE);
INSERT INTO insight_item (category, text_en, text_ko, active) VALUES ('quote', '"Do not spoil what you have by desiring what you have not." — Epicurus', '"갖지 못한 것을 갈망하느라 가진 것을 망치지 마라." — 에피쿠로스', TRUE);
INSERT INTO insight_item (category, text_en, text_ko, active) VALUES ('quote', '"He who is not satisfied with a little, is satisfied with nothing." — Epicurus', '"작은 것에 만족하지 못하는 사람은 그 무엇에도 만족하지 못한다." — 에피쿠로스', TRUE);
INSERT INTO insight_item (category, text_en, text_ko, active) VALUES ('quote', '"We suffer more often in imagination than in reality." — Seneca', '"우리는 실제보다 상상 속에서 더 자주 고통받는다." — 세네카', TRUE);
INSERT INTO insight_item (category, text_en, text_ko, active) VALUES ('quote', '"It is not that we have a short time to live, but that we waste a lot of it." — Seneca', '"인생이 짧은 게 아니라, 우리가 그 많은 부분을 낭비하는 것이다." — 세네카', TRUE);
INSERT INTO insight_item (category, text_en, text_ko, active) VALUES ('quote', '"You have power over your mind, not outside events. Realize this, and you will find strength." — Marcus Aurelius', '"당신은 외부 사건이 아니라 자신의 마음을 다스릴 힘이 있다. 이를 깨달으면 곧 힘을 얻는다." — 마르쿠스 아우렐리우스', TRUE);
INSERT INTO insight_item (category, text_en, text_ko, active) VALUES ('quote', '"Very little is needed to make a happy life; it is all within yourself, in your way of thinking." — Marcus Aurelius', '"행복한 삶에는 아주 적은 것만 필요하다. 그것은 모두 당신의 생각 안에 있다." — 마르쿠스 아우렐리우스', TRUE);
INSERT INTO insight_item (category, text_en, text_ko, active) VALUES ('quote', '"Simplicity is the ultimate sophistication." — Leonardo da Vinci', '"단순함이야말로 궁극의 세련됨이다." — 레오나르도 다빈치', TRUE);
INSERT INTO insight_item (category, text_en, text_ko, active) VALUES ('quote', '"Nature does not hurry, yet everything is accomplished." — Lao Tzu', '"자연은 서두르지 않지만, 모든 것을 이루어낸다." — 노자', TRUE);
INSERT INTO insight_item (category, text_en, text_ko, active) VALUES ('quote', '"When you let go of what you are, you become what you might be." — Lao Tzu', '"지금의 나를 놓아줄 때, 비로소 될 수 있는 나가 된다." — 노자', TRUE);
INSERT INTO insight_item (category, text_en, text_ko, active) VALUES ('quote', '"An empty lantern provides no light. Self-care is the fuel that allows your light to shine brightly." — unknown', '"빈 등불은 빛을 낼 수 없다. 자기 돌봄은 그 빛을 밝게 유지해주는 연료다." — 작자 미상', TRUE);
INSERT INTO insight_item (category, text_en, text_ko, active) VALUES ('quote', '"Sometimes the most productive thing you can do is relax." — Mark Black', '"때로는 쉬는 것이 가장 생산적인 일이다." — 마크 블랙', TRUE);
INSERT INTO insight_item (category, text_en, text_ko, active) VALUES ('quote', '"Take rest; a field that has rested gives a bountiful crop." — Ovid', '"쉬게 하라. 쉬어본 땅이 풍성한 수확을 낸다." — 오비디우스', TRUE);
INSERT INTO insight_item (category, text_en, text_ko, active) VALUES ('quote', '"There is virtue in work and there is virtue in rest. Use both and overlook neither." — Alan Cohen', '"일에도 미덕이 있고 쉼에도 미덕이 있다. 둘 다 쓰고, 어느 것도 소홀히 하지 말라." — 앨런 코헨', TRUE);
INSERT INTO insight_item (category, text_en, text_ko, active) VALUES ('quote', '"Almost everything works again if you unplug it for a few minutes." — Anne Lamott', '"잠깐 코드를 뽑아두면 거의 모든 게 다시 잘 작동한다." — 앤 라모트', TRUE);
INSERT INTO insight_item (category, text_en, text_ko, active) VALUES ('quote', '"The soul usually knows what to do to heal itself. The challenge is to silence the mind." — Caroline Myss', '"영혼은 대개 스스로를 치유하는 법을 알고 있다. 어려운 건 마음을 조용히 시키는 일이다." — 캐롤라인 미스', TRUE);
INSERT INTO insight_item (category, text_en, text_ko, active) VALUES ('quote', '"Within you, there is a stillness and a sanctuary to which you can retreat at any time." — Hermann Hesse', '"당신 안에는 언제든 물러설 수 있는 고요함과 안식처가 있다." — 헤르만 헤세', TRUE);
INSERT INTO insight_item (category, text_en, text_ko, active) VALUES ('quote', '"Wherever you are, be all there." — Jim Elliot', '"어디에 있든, 온전히 그곳에 있으라." — 짐 엘리엇', TRUE);
INSERT INTO insight_item (category, text_en, text_ko, active) VALUES ('quote', '"The best way to capture moments is to pay attention. This is how we cultivate mindfulness." — Jon Kabat-Zinn', '"순간을 붙잡는 가장 좋은 방법은 주의를 기울이는 것이다. 그것이 곧 마음챙김을 키우는 길이다." — 존 카밧진', TRUE);
INSERT INTO insight_item (category, text_en, text_ko, active) VALUES ('quote', '"You are not a drop in the ocean. You are the entire ocean in a drop." — Rumi', '"당신은 바다 속 한 방울이 아니라, 한 방울 안의 온전한 바다다." — 루미', TRUE);
INSERT INTO insight_item (category, text_en, text_ko, active) VALUES ('quote', '"The quieter you become, the more you are able to hear." — Rumi', '"조용해질수록, 더 많이 들을 수 있다." — 루미', TRUE);
INSERT INTO insight_item (category, text_en, text_ko, active) VALUES ('quote', '"Yesterday I was clever, so I wanted to change the world. Today I am wise, so I am changing myself." — Rumi', '"어제는 똑똑해서 세상을 바꾸고 싶었다. 오늘은 지혜로워져서 나 자신을 바꾸고 있다." — 루미', TRUE);
INSERT INTO insight_item (category, text_en, text_ko, active) VALUES ('quote', '"Between stimulus and response there is a space. In that space is our power to choose our response." — Viktor Frankl', '"자극과 반응 사이에는 공간이 있다. 그 공간 안에 우리의 반응을 선택할 힘이 있다." — 빅터 프랭클', TRUE);
INSERT INTO insight_item (category, text_en, text_ko, active) VALUES ('quote', '"What day is it?" "It''s today," squeaked Piglet. "My favorite day," said Pooh.', '"오늘이 무슨 요일이야?" 피글렛이 물었다. "오늘이야." "내가 제일 좋아하는 요일이네." 곰돌이 푸가 말했다.', TRUE);
INSERT INTO insight_item (category, text_en, text_ko, active) VALUES ('quote', '"Doing nothing often leads to the very best of something." — Winnie the Pooh', '"아무것도 안 하는 게 종종 뭔가 가장 좋은 것으로 이어지곤 하지." — 곰돌이 푸', TRUE);
INSERT INTO insight_item (category, text_en, text_ko, active) VALUES ('quote', '"Sometimes I sits and thinks, and sometimes I just sits." — Winnie the Pooh', '"가끔은 앉아서 생각하고, 가끔은 그냥 앉아 있어." — 곰돌이 푸', TRUE);
INSERT INTO insight_item (category, text_en, text_ko, active) VALUES ('quote', '"How lucky I am to have something that makes saying goodbye so hard." — Winnie the Pooh (attributed)', '"작별이 이토록 힘들 만큼 소중한 걸 가졌다니, 나는 참 운이 좋다." — 곰돌이 푸(로 알려짐)', TRUE);
INSERT INTO insight_item (category, text_en, text_ko, active) VALUES ('quote', '"Not all those who wander are lost." — J. R. R. Tolkien', '"방황하는 이들이 모두 길을 잃은 것은 아니다." — J. R. R. 톨킨', TRUE);
INSERT INTO insight_item (category, text_en, text_ko, active) VALUES ('quote', '"It is good to have an end to journey toward, but it is the journey that matters in the end." — Ursula K. Le Guin', '"향해 갈 목적지가 있는 것은 좋지만, 결국 중요한 건 그 여정이다." — 어슐러 K. 르 귄', TRUE);
INSERT INTO insight_item (category, text_en, text_ko, active) VALUES ('quote', '"Life moves pretty fast. If you don''t stop and look around once in a while, you could miss it." — Ferris Bueller''s Day Off', '"인생은 꽤 빨리 지나간다. 가끔 멈춰서 둘러보지 않으면 놓쳐버릴 수도 있다." — 페리스의 해방일지', TRUE);
INSERT INTO insight_item (category, text_en, text_ko, active) VALUES ('quote', '"Almost anything is easier to get into than out of." — Agnes Allen', '"거의 모든 건 들어가기는 쉬워도 빠져나오기는 어렵다." — 애그니스 앨런', TRUE);
INSERT INTO insight_item (category, text_en, text_ko, active) VALUES ('quote', '"The trouble is, you think you have time." — Buddha (attributed)', '"문제는, 당신에게 시간이 있다고 착각한다는 것이다." — 붓다(로 알려짐)', TRUE);
INSERT INTO insight_item (category, text_en, text_ko, active) VALUES ('quote', '"Realize deeply that the present moment is all you ever have." — Eckhart Tolle', '"지금 이 순간이야말로 당신이 가진 전부라는 사실을 깊이 깨달아라." — 에크하르트 톨레', TRUE);
INSERT INTO insight_item (category, text_en, text_ko, active) VALUES ('quote', '"Some people are so poor, all they have is money." — Bob Marley (attributed)', '"어떤 사람들은 너무 가난해서 가진 게 돈밖에 없다." — 밥 말리(로 알려짐)', TRUE);
INSERT INTO insight_item (category, text_en, text_ko, active) VALUES ('quote', '"Happiness is not something ready-made. It comes from your own actions." — Dalai Lama', '"행복은 이미 만들어져 있는 게 아니다. 그것은 나의 행동에서 비롯된다." — 달라이 라마', TRUE);
INSERT INTO insight_item (category, text_en, text_ko, active) VALUES ('quote', '"A calm mind brings inner strength and self-confidence." — Dalai Lama', '"고요한 마음이 내면의 힘과 자신감을 가져다준다." — 달라이 라마', TRUE);
INSERT INTO insight_item (category, text_en, text_ko, active) VALUES ('quote', '"Wrinkles should merely indicate where smiles have been." — Mark Twain', '"주름살은 그저 웃음이 지나간 자리를 표시할 뿐이다." — 마크 트웨인', TRUE);
INSERT INTO insight_item (category, text_en, text_ko, active) VALUES ('quote', '"Twenty years from now you will be more disappointed by the things you didn''t do than by the ones you did do." — Mark Twain', '"20년 후, 당신은 저질렀던 일보다 저지르지 않은 일 때문에 더 후회할 것이다." — 마크 트웨인', TRUE);
INSERT INTO insight_item (category, text_en, text_ko, active) VALUES ('quote', '"Comparison is the thief of joy." — Theodore Roosevelt', '"비교는 기쁨을 훔쳐가는 도둑이다." — 시어도어 루스벨트', TRUE);
INSERT INTO insight_item (category, text_en, text_ko, active) VALUES ('quote', '"To be yourself in a world that is constantly trying to make you something else is the greatest accomplishment." — Ralph Waldo Emerson', '"끊임없이 다른 무언가가 되라고 강요하는 세상에서 나 자신으로 있는 것, 그것이 가장 큰 성취다." — 랄프 왈도 에머슨', TRUE);
INSERT INTO insight_item (category, text_en, text_ko, active) VALUES ('quote', '"Adopt the pace of nature: her secret is patience." — Ralph Waldo Emerson', '"자연의 속도를 따르라. 그 비밀은 인내다." — 랄프 왈도 에머슨', TRUE);
INSERT INTO insight_item (category, text_en, text_ko, active) VALUES ('quote', '"Nothing can bring you peace but yourself." — Ralph Waldo Emerson', '"나 자신 외에는 그 무엇도 내게 평화를 가져다줄 수 없다." — 랄프 왈도 에머슨', TRUE);
INSERT INTO insight_item (category, text_en, text_ko, active) VALUES ('quote', '"Simplify, simplify." — Henry David Thoreau', '"단순하게, 단순하게 살라." — 헨리 데이비드 소로', TRUE);
INSERT INTO insight_item (category, text_en, text_ko, active) VALUES ('quote', '"It''s not what you look at that matters, it''s what you see." — Henry David Thoreau', '"무엇을 바라보느냐가 아니라, 무엇을 보느냐가 중요하다." — 헨리 데이비드 소로', TRUE);
INSERT INTO insight_item (category, text_en, text_ko, active) VALUES ('quote', '"None are so busy as the fool and the knave." — Benjamin Franklin', '"바보와 사기꾼만큼 늘 바쁜 사람은 없다." — 벤저민 프랭클린', TRUE);
INSERT INTO insight_item (category, text_en, text_ko, active) VALUES ('quote', '"Lost time is never found again." — Benjamin Franklin', '"잃어버린 시간은 다시 찾을 수 없다." — 벤저민 프랭클린', TRUE);
INSERT INTO insight_item (category, text_en, text_ko, active) VALUES ('quote', '"The best time to plant a tree was 20 years ago. The second best time is now." — Chinese Proverb', '"나무를 심기 가장 좋은 때는 20년 전이었다. 두 번째로 좋은 때는 바로 지금이다." — 중국 속담', TRUE);
INSERT INTO insight_item (category, text_en, text_ko, active) VALUES ('quote', '"A journey of a thousand miles begins with a single step." — Lao Tzu', '"천 리 길도 한 걸음부터." — 노자', TRUE);
INSERT INTO insight_item (category, text_en, text_ko, active) VALUES ('quote', '"Almost everyone comes to realize that the greatest joys of life are the simplest." — Sylvia Plath (paraphrased sentiment)', '"결국 사람들은 삶의 가장 큰 기쁨이 가장 단순한 것에 있다는 걸 깨닫게 된다." — 실비아 플라스(의 정서를 담아)', TRUE);
INSERT INTO insight_item (category, text_en, text_ko, active) VALUES ('quote', '"You are never too old to set another goal or to dream a new dream." — C. S. Lewis', '"새로운 목표를 세우거나 새로운 꿈을 꾸기에 너무 늦은 나이란 없다." — C. S. 루이스', TRUE);
INSERT INTO insight_item (category, text_en, text_ko, active) VALUES ('quote', '"Golden advice: eat less, chew more; ride less, walk more; worry less, work more; talk less, think more." — attributed proverb', '"황금률: 덜 먹고 더 씹어라, 덜 타고 더 걸어라, 덜 걱정하고 더 일하라, 덜 말하고 더 생각하라." — 오랜 격언', TRUE);
INSERT INTO insight_item (category, text_en, text_ko, active) VALUES ('quote', '"He who has a why to live can bear almost any how." — Friedrich Nietzsche', '"살아야 할 이유가 있는 사람은 그 어떤 방식으로도 견뎌낼 수 있다." — 프리드리히 니체', TRUE);
INSERT INTO insight_item (category, text_en, text_ko, active) VALUES ('quote', '"I am not a product of my circumstances. I am a product of my decisions." — Stephen Covey', '"나는 환경의 산물이 아니라, 내 결정의 산물이다." — 스티븐 코비', TRUE);
INSERT INTO insight_item (category, text_en, text_ko, active) VALUES ('quote', '"The mind is everything. What you think you become." — Buddha (attributed)', '"마음이 전부다. 생각하는 대로 된다." — 붓다(로 알려짐)', TRUE);
INSERT INTO insight_item (category, text_en, text_ko, active) VALUES ('quote', '"Peace comes from within. Do not seek it without." — Buddha (attributed)', '"평화는 내 안에서 온다. 밖에서 찾으려 하지 말라." — 붓다(로 알려짐)', TRUE);
INSERT INTO insight_item (category, text_en, text_ko, active) VALUES ('quote', '"What we think, we become." — Buddha (attributed)', '"생각하는 대로 된다." — 붓다(로 알려짐)', TRUE);
INSERT INTO insight_item (category, text_en, text_ko, active) VALUES ('quote', '"Turn your wounds into wisdom." — Oprah Winfrey', '"상처를 지혜로 바꾸라." — 오프라 윈프리', TRUE);
INSERT INTO insight_item (category, text_en, text_ko, active) VALUES ('quote', '"You get in life what you have the courage to ask for." — Oprah Winfrey', '"인생에서 얻는 것은 요청할 용기가 있는 만큼이다." — 오프라 윈프리', TRUE);
INSERT INTO insight_item (category, text_en, text_ko, active) VALUES ('quote', '"Almost everything will work again if you give it a rest." — modern proverb', '"거의 모든 것은 잠시 쉬게 해주면 다시 잘 작동한다." — 현대 격언', TRUE);
INSERT INTO insight_item (category, text_en, text_ko, active) VALUES ('quote', '"There is more to life than increasing its speed." — Mahatma Gandhi', '"삶에는 속도를 높이는 것보다 더 중요한 것이 있다." — 마하트마 간디', TRUE);
INSERT INTO insight_item (category, text_en, text_ko, active) VALUES ('quote', '"A man is but the product of his thoughts. What he thinks, he becomes." — Mahatma Gandhi', '"인간은 자기 생각의 산물일 뿐이다. 생각하는 대로 그가 된다." — 마하트마 간디', TRUE);
INSERT INTO insight_item (category, text_en, text_ko, active) VALUES ('tip', 'Wave your hand toward the camera to skip to the next video — no need to touch the screen', '카메라 쪽으로 손을 훠이 밀어보세요. 화면을 안 만져도 다음 영상으로 넘어가요', TRUE);
INSERT INTO insight_item (category, text_en, text_ko, active) VALUES ('tip', 'Any Bluetooth remote works — the volume button doubles as next-video', '블루투스 리모컨은 아무거나 괜찮아요. 볼륨 버튼이 다음 영상 버튼이 돼요', TRUE);
INSERT INTO insight_item (category, text_en, text_ko, active) VALUES ('tip', 'Hand-wave works best up close, pushed toward the camera in one smooth motion', '손짓은 카메라 가까이에서, 화면 쪽으로 슥 한 번에 밀어주면 제일 잘 잡혀요', TRUE);
INSERT INTO insight_item (category, text_en, text_ko, active) VALUES ('tip', 'Tap the P button for Open App, Shorts HOT, and Favorites — all in one place', 'P 버튼을 누르면 앱 열기, 쇼츠 HOT, 즐겨찾기까지 한 번에 볼 수 있어요', TRUE);
INSERT INTO insight_item (category, text_en, text_ko, active) VALUES ('tip', 'Loving a video? Add it to Favorites right from the player', '지금 보는 영상이 마음에 들면, 그 자리에서 바로 즐겨찾기에 추가할 수 있어요', TRUE);
INSERT INTO insight_item (category, text_en, text_ko, active) VALUES ('tip', 'Fall asleep watching, and the session ends itself. No need to worry about dozing off', '보다가 잠들면 세션이 알아서 꺼져요. 폰 붙잡고 잘까 봐 걱정 안 해도 돼요', TRUE);
INSERT INTO insight_item (category, text_en, text_ko, active) VALUES ('tip', 'Every 20 minutes, a quiet nudge to rest your eyes and neck', '20분마다 조용히 쉬라고 알려드려요. 눈도 목도 쉴 시간이에요', TRUE);
INSERT INTO insight_item (category, text_en, text_ko, active) VALUES ('tip', 'Hands-free mode lets you skip videos without lifting a finger', '핸즈프리 모드를 켜두면 손 하나 까딱 안 하고 영상을 넘길 수 있어요', TRUE);
INSERT INTO insight_item (category, text_en, text_ko, active) VALUES ('tip', 'Remote or gesture too much hassle? Just swipe by hand — you''re never required to use either', '리모컨도 손짓도 귀찮으면 그냥 손으로 넘겨도 돼요. 둘 다 억지로 안 써도 됩니다', TRUE);
INSERT INTO insight_item (category, text_en, text_ko, active) VALUES ('tip', 'Today''s limit isn''t fixed — change it anytime from Settings', '오늘 목표 시간은 고정이 아니에요. 설정에서 언제든 바꿀 수 있어요', TRUE);
INSERT INTO insight_item (category, text_en, text_ko, active) VALUES ('tip', 'Shorts HOT collects what''s trending right now, sorted by category', 'Shorts HOT엔 요즘 많이 보는 영상들이 카테고리별로 모여 있어요', TRUE);
INSERT INTO insight_item (category, text_en, text_ko, active) VALUES ('tip', 'Videos you save to Favorites are waiting for you back in the Focus tab', '즐겨찾기에 저장한 영상은 나중에 집중 탭에서 다시 꺼내볼 수 있어요', TRUE);
INSERT INTO insight_item (category, text_en, text_ko, active) VALUES ('tip', 'Ran out of time but need a bit more? Extend Time adds minutes just for today', '시간이 부족한데 조금만 더 필요하면, Extend Time으로 오늘 하루만 늘릴 수 있어요', TRUE);
INSERT INTO insight_item (category, text_en, text_ko, active) VALUES ('tip', 'Break reminders and daily limits can each be turned off separately if one isn''t for you', '휴식 알림이랑 하루 제한, 둘 중 하나만 필요하면 따로 꺼둘 수 있어요', TRUE);
INSERT INTO insight_item (category, text_en, text_ko, active) VALUES ('tip', 'The daily streak resets if a day is skipped, but past checkmarks on the weekly calendar stay recorded', '연속 출석은 하루라도 건너뛰면 끊기지만, 지난 요일 체크 표시는 그대로 남아 있어요', TRUE);
INSERT INTO insight_item (category, text_en, text_ko, active) VALUES ('stat_yesterdayLastWatched', 'You were still watching at {{time}} yesterday', '어제는 {{time}}까지 보고 계셨네요', TRUE);
INSERT INTO insight_item (category, text_en, text_ko, active) VALUES ('stat_yesterdayLastWatched', 'Your last video yesterday was at {{time}}. Remember that?', '어제 마지막 영상, {{time}}이었어요. 기억나세요?', TRUE);
INSERT INTO insight_item (category, text_en, text_ko, active) VALUES ('stat_yesterdayLastWatched', '{{time}} yesterday — that was your stopping point', '어제 {{time}}에 멈추셨더라고요', TRUE);
INSERT INTO insight_item (category, text_en, text_ko, active) VALUES ('stat_yesterdayLastWatched', 'Yesterday wrapped up at {{time}}. A new day, a clean slate', '어제는 {{time}}에 마무리됐어요. 오늘은 새로운 하루예요', TRUE);
INSERT INTO insight_item (category, text_en, text_ko, active) VALUES ('stat_yesterdayLastWatched', 'Last night, {{time}} was your final scroll', '어젯밤 {{time}}이 마지막 스크롤이었어요', TRUE);
INSERT INTO insight_item (category, text_en, text_ko, active) VALUES ('stat_todayMoreThanAvg', 'You''re already {{diff}} min over your usual today', '오늘 벌써 평소보다 {{diff}}분 더 보고 있어요', TRUE);
INSERT INTO insight_item (category, text_en, text_ko, active) VALUES ('stat_todayMoreThanAvg', '{{diff}} min past your average. Time for an eye break?', '평균보다 {{diff}}분 초과. 슬슬 눈 좀 쉬어줄까요?', TRUE);
INSERT INTO insight_item (category, text_en, text_ko, active) VALUES ('stat_todayMoreThanAvg', 'A {{diff}}-minute bigger day than usual — worth a quick stretch', '평소보다 {{diff}}분 더 긴 하루네요 — 스트레칭 한 번 어때요', TRUE);
INSERT INTO insight_item (category, text_en, text_ko, active) VALUES ('stat_todayMoreThanAvg', '{{diff}} extra minutes today. No judgment, just a nudge', '오늘 {{diff}}분 더 봤어요. 혼내는 거 아니에요, 그냥 살짝 알려드리는 거예요', TRUE);
INSERT INTO insight_item (category, text_en, text_ko, active) VALUES ('stat_todayMoreThanAvg', 'Above average by {{diff}} min — your future self might thank you for a pause', '평균보다 {{diff}}분 초과 중 — 지금 잠깐 멈추면 내일의 내가 고마워할지도', TRUE);
INSERT INTO insight_item (category, text_en, text_ko, active) VALUES ('stat_todayLessThanAvg', 'You''re {{diff}} min under your average today — nice pace', '오늘은 평균보다 {{diff}}분 덜 봤어요 — 좋은 흐름이에요', TRUE);
INSERT INTO insight_item (category, text_en, text_ko, active) VALUES ('stat_todayLessThanAvg', 'Good pace today — {{diff}} min saved vs your average', '오늘 페이스 괜찮은데요? 평균보다 {{diff}}분 절약 중', TRUE);
INSERT INTO insight_item (category, text_en, text_ko, active) VALUES ('stat_todayLessThanAvg', '{{diff}} minutes lighter than usual. Small wins count', '평소보다 {{diff}}분 가벼운 하루예요. 작은 성취도 성취예요', TRUE);
INSERT INTO insight_item (category, text_en, text_ko, active) VALUES ('stat_todayLessThanAvg', '{{diff}} min under average — you''re steering this, not the algorithm', '평균보다 {{diff}}분 적어요 — 알고리즘이 아니라 내가 방향을 정하고 있다는 뜻이에요', TRUE);
